# Generated by Django 4.0.5 on 2022-07-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='intro',
            fields=[
                ('rollno', models.CharField(max_length=122, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('number', models.CharField(max_length=122)),
                ('linkd', models.CharField(max_length=122)),
                ('github', models.CharField(max_length=122)),
                ('university', models.CharField(max_length=122)),
                ('degree', models.CharField(max_length=122)),
                ('branch', models.CharField(max_length=122)),
                ('cg', models.DecimalField(decimal_places=2, max_digits=3)),
                ('school', models.CharField(max_length=122)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
