# Generated by Django 4.0.5 on 2022-07-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='year',
            field=models.DecimalField(decimal_places=0, default=2024, max_digits=4),
        ),
    ]
